### DISCUSSION TITLE
How to enable HW acceleration in Docker

### DISCUSSION THREAD

**Discussion by kraizelburg** [stashapp/stash#4439] [Q&A] [answered]
Hi,

I would like to know how to enable HW acceleration in docker, I have tried adding:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
to my docker compose and also enable hw transcoding in settings but I cannot make it work. 
My host is a mini pc with debian server.

Thanks

**Comment by DogmaDragon** [comment]
Try steps from https://github.com/stashapp/stash/issues/305#issuecomment-1832488359

**Comment by feederbox826** [comment, marked as answer]
after passing through /dev/dri, you can use these options to enable hwaccel

https://github.com/feederbox826/stash-s6/blob/main/docs/hwaccel.md

you'll need a corresponding image built with hwaccel in mind - 

[stash-s6](https://github.com/feederbox826/stash-s6/pkgs/container/stash-s6) is my project, there is also [stash-jellyfin](https://github.com/nerethos/stash-jellyfin-ffmpeg), a manual build [from source](https://github.com/stashapp/stash/tree/develop/docker/build/x86_64) and my other personal project, [stash-cuda](https://github.com/feederbox826/stash-cuda)

alpine does not support hwaccel because it lacks the propreitary driver support for most hardware acceleration

**Comment by fleischereiahmet** [comment]
Hey Guys, i´m sorry if i am abusing this Q&A but did anybody managed to get hwaccel work on LXC Containers or could help me through it? 

I was able to passthrough the iGPU to the LXC and installed the intel-gpu-tools but it doesn´t seem to work..

**Reply by Anubarak** [reply]
Same here, I guess you were not able to make it work were you?
I followed the steps but it doesn't seem to work, there is no error tho.

**Reply by fleischereiahmet** [reply]
Hi Robin, after lots of research and trying i found out the docker of feederbox was finally working:
https://github.com/feederbox826/stash-s6
idk which environment, gpu etc you´re using but in my case it was an LXC Container on Proxmox with an iGPU on an intel i5

hope this helps you.

**Reply by Anubarak** [reply]
Thank you very much.
I have nearly the same setup that's why I asked. Proxmox lxc iGPU i5 nearly everything is working and I can manually transcode inside the container without any issues.

However stash itself never uses my iGPU and instead always the wrong command with the CPU

It always uses `-c:v libx264` instead of `-c:v h264_vaapi`

So default stash command without hardware transcoding
> /usr/bin/ffmpeg -hide_banner -v error -i /file.mp4 -c:v libx264 -pix_fmt yuv420p -preset veryfast -crf 25 -sc_threshold 0 -movflags frag_keyframe+empty_moov -vf scale=-2:720 -ac 2 -f mp4

And I just need stash to use my hardware instead with 
>  /usr/bin/ffmpeg -hide_banner -v error -i /file.mp4 -c:v h264_vaapi -pix_fmt yuv420p -preset veryfast -crf 25 -sc_threshold 0 -movflags frag_keyframe+empty_moov -vf scale=-2:720 -ac 2 -f mp4

Seems like I'll have to try stash-s6 thanks again, I left those info above just in case someone else runs into the same issue or someone knows how to change the command stash uses. All in all I just need to replace one part, maybe there is a way for the owner to make it possible to adjust it 😅

**Reply by fleischereiahmet** [reply]
did you also edit your lxc.conf to passthrough the igpu?

which info are you getting when you check the logs?

if everything is configured correctly you should see something like:


Info    
[InitHWSupport] Supported HW codecs [4]:
	H264 Intel Quick Sync Video (QSV) - h264_qsv
	H264 Intel Quick Sync Video (QSV) Compatibility profile - h264_qsv
	H264 VAAPI - h264_vaapi
	VP9 VAAPI - vp9_vaapi

**Reply by Anubarak** [reply]
Yes I passed it otherwise it wouldn't work with a custom command. As said when I login to my docker container  via docker exec -it and run the correct command everything works. Stash just doesn't use my iGPU with it's command and instead requests my CPU for whatever reason so I just need to make it use the iGPU.


The logs in the stash settings show nothing interesting/nothing like that when I start a video. Or are you talking about other logs somewhere else?

**Reply by fleischereiahmet** [reply]
If you go in Stash to Settings and on the left sidebar to Logs you should see something similar like this:

Info
[InitHWSupport] Supported HW codecs [4]:
H264 Intel Quick Sync Video (QSV) - h264_qsv
H264 Intel Quick Sync Video (QSV) Compatibility profile - h264_qsv
H264 VAAPI - h264_vaapi
VP9 VAAPI - vp9_vaapi

if not, stash is not recognizing your GPU

you can check if the HW transcode is working by typing in your lxc:
intel_gpu_top 
provided you have the tool installed

Sorry for more questions :D just trying to put everything in a frame:

how is your docker compose look like?

did you install the necessary drivers such as:
sudo apt install -y curl git ffmpeg intel-media-va-driver-non-free i965-va-driver vainfo

at least it was helpful for me 

if you type in your lxc:
ls /dev/dri/
do you see the igpu ?

if i understood you correctly you already add the following commands in order to passthrough the ipgu to you lxc, correct?

lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
lxc.mount.entry: /dev/dri/card0 dev/dri/card0 none bind,optional,create=file

**Reply by Anubarak** [reply]
Thank you for your answer

> If you go in Stash to Settings and on the left sidebar to Logs you should see something similar like this:
Info
[InitHWSupport] Supported HW codecs [4]:
H264 Intel Quick Sync Video (QSV) - h264_qsv
H264 Intel Quick Sync Video (QSV) Compatibility profile - h264_qsv
H264 VAAPI - h264_vaapi
VP9 VAAPI - vp9_vaapi
if not, stash is not recognizing your GPU

I can see this
```
2025-08-19 18:31:13
Info    
[InitHWSupport] Supported HW codecs [2]:
	H264 VAAPI - h264_vaapi
	VP9 VAAPI - vp9_vaapi
2025-08-19 18:31:12
Info    
using config file: /root/.stash/config.yml
```

> you can check if the HW transcode is working by typing in your lxc:
intel_gpu_top
provided you have the tool installed

I never got this to work unfortunatly.. I always receive permission denied in every lxc - even in Plex where everything is working.


> Sorry for more questions :D just trying to put everything in a frame:
No no, I really appreciate your questions and your time. Thank you very much.

> how is your docker compose look like?
```
# APPNICENAME=Stash
# APPDESCRIPTION=An organizer for your porn, written in Go
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "9999:9999"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - ./config:/root/.stash
      - /mnt/media:/data
      - ./metadata:/metadata
      - ./cache:/cache
      - ./blobs:/blobs
      - ./generated:/generated
    devices:
      - /dev/dri:/dev/dri # This line is the key addition
    command: sh -c "apk add --no-cache intel-media-driver && exec /usr/bin/stash"
```

> did you install the necessary drivers such as:
sudo apt install -y curl git ffmpeg intel-media-va-driver-non-free i965-va-driver vainfo

I didn't try that, but I get the following error
```
/ # apk add curl git ffmpeg intel-media-va-driver-non-free i965-va-driver vainfo
ERROR: unable to select packages:
  i965-va-driver (no such package):
    required by: world[i965-va-driver]
  intel-media-va-driver-non-free (no such package):
    required by: world[intel-media-va-driver-non-free]
  vainfo (no such package):
    required by: world[vainfo]
```
Sorry if I made a mistake here - my Linux skills are limited

> if you type in your lxc:
ls /dev/dri/
do you see the igpu ?

Yes, my proxmox host, my plex LXC and my stash LXC as well as my stash docker all show the same results here and all contain my iGPU

> if i understood you correctly you already add the following commands in order to passthrough the ipgu to you lxc, correct?

I did it like that:
```
dev0: /dev/dri/card0,gid=44
dev1: /dev/dri/renderD128,gid=104
```
that was directly taken by my plex LXC installed via Proxmox helper script, I wasn't able to pass my iGPU in your way.

Again thank you very much for your help
