### DISCUSSION TITLE
Reverse Proxy with NGINX resulting in 400 Bad Request

### DISCUSSION THREAD

**Discussion by Quixelated** [stashapp/stash#4809] [Q&A]
Hello! I've got Stash running on my Windows machine, and I'm trying to get https up and running so I can reach it from outside my network. I'm using NGINX, and I'm just getting a 400 Bad Request. I don't see any mentions of the issue in the NGINX error log (even with it set to info) or in Stash at any log level.

Relevant NGINX Entry
```
##STASH Server##
    
    server {
listen [::]:80;
listen 80;
listen [::]:443 ssl;
listen 443 ssl;
    server_name stash.[REDACTED]; 
    
        ssl_session_timeout 30m;
        ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_certificate      SSL/cert2.pem;
    ssl_certificate_key  SSL/private2.key;
        ssl_session_cache shared:SSL:10m;
    
        #add_header Public-Key-Pins '
        #pin-sha256="8TzXdhbnv+l6EjDG2Vj9EmgGiSmZenrTZSNaUFEwyUE="; 
        #pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; 
        #pin-sha256="Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys="; 
        #max-age=86400; includeSubDomains';
        
        add_header X-Xss-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Strict-Transport-Security "max-age=2592000; includeSubdomains" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        proxy_hide_header X-Powered-By;
        add_header 'Referrer-Policy' 'no-referrer';
        add_header Content-Security-Policy "r.cjwinn.net;";
        
    
     location / {
        proxy_pass http://127.0.0.1:9999;  

        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #Next three lines allow websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        #Next lines added from Stash documentation
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60000s;
        proxy_set_header Host $http_host;
        }

}
```

Stash config.yml
```
api_key: [REDACTED]
blobs_path: blobs
blobs_storage: FILESYSTEM
cache: cache
calculate_md5: false
create_image_clip_from_videos: false
dangerous_allow_public_without_auth: "false"
database: stash-go.sqlite
defaults:
    scan_task:
        scangeneratecovers: true
        scangeneratepreviews: true
        scangenerateimagepreviews: true
        scangeneratesprites: true
        scangeneratephashes: true
        scangeneratethumbnails: true
        scangenerateclippreviews: true
external_host: https://stash.[REDACTED]
gallery_cover_regex: (poster|cover|folder|board)\.[^\.]+$
generated: generated
host: 0.0.0.0
jwt_secret_key: f82f8154ebee5df72b29353ff42b7c4ec2b0dad63cb29c6f3f2d29f1afb9b246
no_proxy: localhost,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
nobrowser: false
notifications_enabled: true
parallel_tasks: 1
password: [REDACTED]
plugins:
    package_sources:
        - localpath: community
          name: Community (stable)
          url: https://stashapp.github.io/CommunityScripts/stable/index.yml
plugins_path: E:\other\stash\plugins
port: 9999
preview_audio: true
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scrapers:
    package_sources:
        - localpath: community
          name: Community (stable)
          url: https://stashapp.github.io/CommunityScrapers/stable/index.yml
scrapers_path: E:\other\stash\scrapers
security_tripwire_accessed_from_public_internet: ""
sequential_scanning: false
session_store_key: [REDACTED]
show_one_time_moved_notification: false
sound_on_preview: false
stash:
    - excludeimage: false
      excludevideo: false
      path: E:\other\zzz
theme_color: '#202b33'
ui:
    advanced_mode: true
    front_page_content:
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_released_objects
            values:
                objects: Scenes
          mode: SCENES
          sort_by: date
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_added_objects
            values:
                objects: Studios
          mode: STUDIOS
          sort_by: created_at
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_released_objects
            values:
                objects: Movies
          mode: MOVIES
          sort_by: date
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_added_objects
            values:
                objects: Performers
          mode: PERFORMERS
          sort_by: created_at
        - __typename: CustomFilter
          direction: DESC
          message:
            id: recently_released_objects
            values:
                objects: Galleries
          mode: GALLERIES
          sort_by: date
    last_note_seen: "20240228"
username: admin
video_file_naming_algorithm: OSHASH
write_image_thumbnails: true
```
