### DISCUSSION TITLE
Change / Relocate Scene Details

### DISCUSSION THREAD

**Discussion by nathanstreetx** [stashapp/stash#5555] [Q&A] [answered]
I feel like some information in the details tab doesn't need to be there, specifically the 'Created At' and 'Updated At' information should be under the History Tab not Details. (Or just remove it all together)
![image](https://github.com/user-attachments/assets/f0c60532-8505-46d5-9484-009758239d50)

I also don't think we the the Details Title. Not the content, just the title.
![image](https://github.com/user-attachments/assets/707f53bb-0468-404f-991c-e562a1333912)

Ultimately, I would like the details tab to look like this.
![image](https://github.com/user-attachments/assets/c0917f56-dc4f-486e-b0c6-6fc19e3a309b)

If anyone knows any CSS code that could help me achieve the above.

**Comment by DogmaDragon** [comment]
There are several WIP branches that update the details tab styling. Feedback is welcome.
- https://github.com/stashapp/stash/pull/4582
- https://github.com/stashapp/stash/pull/4699
- https://github.com/stashapp/stash/pull/4785

If you just want to modify it to your preference, you can ask for community help. https://docs.stashapp.cc/#support

**Comment by echo6ix** [comment, marked as answer]
You can remove the `Created at` and `Updated at` fields using the following CSS (mileage may vary I haven't tested this extensively)

```css
[class="tab-content"] {  
    [class*=-details] {
        /* Hide CREATED AT and UPDATED AT fields */
        &> h6:nth-of-type(-n+2) {
            display: none;
        }
    }
}
```

Cannot accomplish your other requests with CSS alone.
