### DISCUSSION TITLE
[Question] Docker/Docker-Compose - How to "create system" and load /data directly at first start of docker image

### DISCUSSION THREAD

**Discussion by milkmandoor** [stashapp/stash#5571] [Q&A]
The docker-compose file suggest putting the data we want our library to be in `/data` inside the docker container. I would have thought this was designed so that the directory would be automatically added to the library and scanned but this isn't the case. 

Is there a way to make stash directly:
-  Add `/data` as a Directory to be scanned
- "create the system" as displayed on the landing page
- Do a full Scan of the library (and thus of the `/data` directory)

so that we can fully automate the initialization of a ready-to-use stash instance without any manual action ?

I don't see any option in the CLI relevant to this.

**Comment by DogmaDragon** [comment]
You can bypass install wizard by manually setting up `config.yml` configuration file.

There is an [API](https://docs.stashapp.cc/api/) you can use to trigger a scan automatically. So you could write entry script to run as part of container start.

**Reply by milkmandoor** [reply]
Correct me if I'm wrong but AFAIK there is absolutely no documentation on how to configure stash via the `config.yml` file, only in-app settings. Do you know of a minimal working config file setup ? Because a lot of things seem to be required.

**Reply by DogmaDragon** [reply]
I don't know exactly, but going through setup generated this `config.yml` with all the defaults selected. 

```yaml
blobs_path: <path>
blobs_storage: FILESYSTEM
cache: <path>
create_image_clip_from_videos: false
dangerous_allow_public_without_auth: "false"
database: <path>
gallery_cover_regex: (poster|cover|folder|board)\.[^\.]+$
generated: 
host: 0.0.0.0
no_proxy: localhost,127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
nobrowser: false
notifications_enabled: true
parallel_tasks: 1
plugins: <path>
    package_sources:
        - localpath: community
          name: Community (stable)
          url: https://stashapp.github.io/CommunityScripts/stable/index.yml
plugins_path: <path>
port: 9999
preview_audio: true
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scrapers:
    package_sources:
        - localpath: community
          name: Community (stable)
          url: https://stashapp.github.io/CommunityScrapers/stable/index.yml
scrapers_path: <path>
security_tripwire_accessed_from_public_internet: ""
sequential_scanning: false
show_one_time_moved_notification: false
sound_on_preview: false
stash: []
theme_color: '#202b33'
ui:
    lastNoteSeen: 20240826
write_image_thumbnails: true
```

Replace `<path>` with paths to your directories.
