### ISSUE TITLE
[Feature] Enable Studio Name and URL placeholder fields for Scrapers

### ISSUE THREAD

**Issue by SmartCap66** [stashapp/stash#1183]
**Is your feature request related to a problem? Please describe.**
I have many media files from various different Studios, I use the existing functionality in the application to mass edit and assign a Studio to each. While a functional URL scraper exists for the Studio the problem I'm having is finding and assigning the correct URL to each file in an efficient manner. My manual method involves performing a web search for the Title/Filename and including the Studio Name or URL, then manually copy/paste/save the URL to each item. Since most search engines support the "site:" operator it's easy to limit my results to return a URL compatible with the existing scrapers. I'd like to help automate this process by writing a generic scraper that performs a web search and assigns the top URL returned, which in my testing is correct/ideal 90%+ of the time.

**Describe the solution you'd like**
I've written a very basic XPath based scraper that functions well and uses the Title field information during the search but I currently need to statically set the Studio Name or URL to refine my results enough for it to be effective. As such I'd like to have access to {studioName} and {studioURL} placeholder fields in the scraper so nothing needs to be statically set and the scraper overall will apply to any Studio's files. Note, Bing is used merely because I found its HTML output more easily parsed by XPath.

```
name: Bing

sceneByFragment:
  action: scrapeXPath
  queryURL: https://www.bing.com/search?q=site%3A{studioURL}+{title}
  # constructs the search query URL from the title or filename (exlcuding extension)
  queryURLReplace:
    title:
      # replace spaces in title with +
      - regex: \s+
        with: "+"
  scraper: sceneScraper

xPathScrapers:
  sceneScraper:
    scene:
      URL: //ol/li/h2/a/@href[1]
```

**Describe alternatives you've considered**
Statically setting or just exempting the Studio information is possible but leads to poor results. I can also add additional Studio information to the Title field in the Web UI, save, then run the script to fetch the URL. Neither of these options scales very well when dealing with a large number of items.

**Additional context**
Overall I'm trying to make use of the existing scrapers to populate the metadata for a large number of newly scanned media files in a time efficient manner. Given that search engines make available large repositories of information it makes sense to try and leverage it to transform a semi unique values like Title/Filename into something more precise, like a URL.
