### ISSUE TITLE
[Bug Report] HTML doesn't render in scene description field from scraper content.

### ISSUE THREAD

**Issue by jeremymeyers** [stashapp/stash#1333]
**Describe the bug**
When scraping scene info, any HTML code contained within the description field does not get rendered.

**To Reproduce**
1. In scene view, scrape a scene with HTML code. Example used: https://www.evilangel.com/en/video/I-Am-Angela-Ep-4-Ciao-Bella/134759
2. hit "Save"
3. view info tab.

**Expected behavior**
Suggest HTML code be stripped out on scrape, both to sidestep this issue and to close a potential security vulnerability.

**Screenshots**

![Screenshot 2021-04-22 00 14 39](https://user-images.githubusercontent.com/3514095/115654774-d511b600-a2ff-11eb-912e-423c71b31f5d.png)

![Screenshot 2021-04-22 00 15 40](https://user-images.githubusercontent.com/3514095/115654841-f83c6580-a2ff-11eb-9f6b-fd181f3fe159.png)

**Stash Version: (from Settings -> About):** 
0.6

**Desktop (please complete the following information):**
Windows/Firefox

**Comment by WithoutPants** [comment]
We'll need the scraper used to reproduce.

**Comment by bnkai** [comment]
The specific scraper used `GammaEntertainment` uses the script part of the page to get the  details. This isnt and shouldnt be parsed. In this cases you can report that in the Community  scraper repo (broken scrapers issue) so that an extra regex is added to remove the <strong> parts. I would also use latest Gammma scraper as it removes the br's already.

```yaml
      Details:
        selector: $detailscript
        postProcess:
          - replace:
              - regex: .+(?:sceneDescription":")(.+)(?:","sceneActors).+
                with: $1
              # Second regex in case no description is provided.
              - regex: .+(?:"sceneDescription":"").+
                with:
              - regex: <\\\/br>|<br\s\\\/>|<br>|<br\\/>
                with: "\n"
```
