### ISSUE TITLE
[Bug Report] Setup Wizard don't give a correct Scraper/Plugin path

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#1356]
**Describe the bug**
The plugins and scrapers are not set properly for a new config. You need to manually edit the config.yml to be able to use Scrapers or plugins.

**To Reproduce**
1. Start a fresh new config (Rename your config.yml...)
2. Get on Setup Wizard
3. Press Next for everything until the setup is done. ($Home/.stash or Working Dir don't matter)
4. Check your config.yml for scraper_path. It will be `scrapers` not `C:\Users\USERNAME\.stash\scrapers`

**Expected behavior**
A correct path.

**Part of config.yml**
```yml
parallel_tasks: 1
plugins_path: plugins
port: 9999
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scrapers_path: scrapers
session_store_key: 535a6c81fb2f3dbaaca6bb4f399bafbb788d86099b8d0660aa2fe2c6d704c5f0
show_studio_as_text: false
slideshow_delay: 5000
```

**Stash Version: (from Settings -> About):**

Version: | v0.6.0-54-g597576f5
-- | --
Build hash: | 597576f5
Build time: | 2021-04-29 01:43:08

**Desktop (please complete the following information):**
 - Windows10
 - Firefox 88.0
