### ISSUE TITLE
[Feature] Pass filename to scraper script

### ISSUE THREAD

**Issue by TaylorSwiftFan13** [stashapp/stash#1554]
I've been working on a scraper/script that parses filenames. 
However it would be more useful to me if I could get the raw filename of the scene. Currently I can only get the "title" which is usually the filename, but sometimes it's not because I've previously changed it or something.

My .yml looks like this:

```
sceneByFragment:
        action: script
        script:
               	- python
                - 1test.py
```

Reading `sys.stdin.read()` in the python script I get:

`{"clientMutationId":null,"id":"6633","title":"Intriguing title goes here","details":"","url":"","date":"2021-07-03","rating":null,"organized":null,"studio_id":"15","gallery_ids":[],"performer_ids":["119"],"movies":[],"tag_ids":[],"cover_image":null,"stash_ids":[]}`

Would be really useful if it also had a "filename" field which contained the base filename of the video.

I've tried adding `{filename}` (because I saw queryURL can use it) as a parameter to the script like this:
```
sceneByFragment:
        action: script
        script:
               	- python
                - 1test.py
                - {filename}
```

but it errors out:

```
[31mERRO[0m[2021-07-04 12:38:10] Error loading scraper /root/.stash/scrapers/1test.yml: yaml: unmarshal errors:

line 8: cannot unmarshal !!map into string
```

**Comment by gitgiggety** [comment]
The error you're getting is related to invalid YAML. This as `{` and `}` are used to open and close objects. You should thus put the value in quotes, so it will be interpreted s string.

```yaml
sceneByFragment:
        action: script
        script:
                - python
                - 1test.py
                - '{filename}'
```

But my guess would be this doesn't work anyway (and will just pass a literal `{filename}` argument) and should be added to the info send to the script using stdin.
