### ISSUE TITLE
[Bug Report] wrong urls on server with custom port

### ISSUE THREAD

**Issue by Froghut** [stashapp/stash#1999]
**Describe the bug**
I have stash running on a server with a custom port, i.e. https://stash.xx.com:1234/ - and all images/videos (like scene previews, videos, etc.) have urls with a duplicate port, i.e. https://stash.xx.com:1234/:1234/scene/123/... and will of course not show / work.

**To Reproduce**
Host on a server thats not on the default port 80 / 443

**Expected behavior**
links to images/videos should not duplicate the port number

**Stash Version: (from Settings -> About):**
Version: v0.10.0
Build hash: f4b7838
running in docker

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox / Edge
 - Version 94 / 95

**Comment by InfiniteTF** [comment]
@Froghut I've tried to reproduce this everywhich way I can think of, with no luck. Can you post your docker config, and reverse proxy config if you're using that?

**Comment by Froghut** [comment]
this is my docker config which includes the traefik reverse-proxy config:

```
  stash:
    container_name: stash
    image: stashapp/stash:latest
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 192.168.91.30
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - X:/Stash/videos:/data
      - c:/docker/stash:/root/.stash
      - X:/Stash/metadata:/metadata
      - X:/Stash/cache:/cache
      - X:/Stash/generated:/generated
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.stash-rtr_r.entrypoints=https"
      - "traefik.http.routers.stash-rtr_r.rule=Host(`stash.xx.com`)"
      - "traefik.http.routers.stash-rtr_r.middlewares=httpsRedirect"
      - "traefik.http.routers.stash-rtr.entrypoints=https"
      - "traefik.http.routers.stash-rtr.rule=Host(`stash.xx.com`)" 
      - "traefik.http.routers.stash-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.stash-rtr.service=stash-svc"
      - "traefik.http.services.stash-svc.loadbalancer.server.port=9999"
```
