### ISSUE TITLE
[Feature] Add a thumbnail size slider to the Performers page

### ISSUE THREAD

**Issue by CupOnMyTable** [stashapp/stash#2201]
The scenes page has a slider which can be used to increase or decrease the thumbnails size on the page.

It would be good to have this on the Performers page too so that the screen real estate can be easily changed as needed.

Thanks.

**Comment by philpw99** [comment]
Use the custom css to control the size then:
```css
.performer-image-container{
  flex: 0 0 50%;
  max-width: 50%;
}

.col-md-8 {
  flex: 0 0 50%;
  max-width: 50%;
}
```
