### ISSUE TITLE
[Bug Report] Player missing on desktop <1200px

### ISSUE THREAD

**Issue by mikorobin** [stashapp/stash#2235]
**Describe the bug**
When I'm using Stash on desktop and the browser window width is less then 1200px (column layout) video player is missing. When I resize it and layout changes to row - player is there.

**To Reproduce**
1. Resize your browser window to be less then 1200px in width
2. Go to single scene view

**Expected behavior**
I expect player to be available despite window size. I remember it being there a few versions earlier.

**Screenshots**
![s1](https://user-images.githubusercontent.com/97420374/149507021-dccb056d-bfe3-4b73-be67-9489ae09afb5.png)

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera 82.0.4227.43 (Chromium based)
 - Version: v0.12.0

**Comment by peolic** [comment]
Did you, by chance, add the custom CSS to hide the scrubber that's usually underneath the video?
If you did, the CSS is now outdated, and you need to **remove** this part:
```css
/* [Scenes tab] Max out the scene player's height */

#jwplayer-container > div:first-child {
  height: 100%;
}
```
