### ISSUE TITLE
Recommendations plugins

### ISSUE THREAD

**Issue by Belleyy** [stashapp/stash#2675]
**Is your feature request related to a problem? Please describe.**
Showing data from outside of your Stash in the recommendations page.

**Describe the solution you'd like**
A new sort of plugin (Task, Hook & this new). It will be a new type in the popup "Add" in the Customise page called "Plugins" with a drop-down showing available plugin.
![image](https://user-images.githubusercontent.com/23707269/173893560-a9619f10-994b-4a80-9a40-2b89e699ccbc.png)
![image](https://user-images.githubusercontent.com/23707269/173893736-159ecc0b-b3d8-4fef-b538-93aa66ae409c.png)

The plugin will be trigger when you open the page, the plugin will return a list of certain data (performer, scenes, ...) and Stash use it.

To be able to know what type of data you sent in the list (and know how Stash will display it):
- a option need to be create in the yml (`type` ?)
- Stash could detect what type of data it's is ? (`scenes: []` use scene display, `performers: []` use performers display)
- Stash don't care, if a single list contain movie & performer & scene, it will display them like that in the same slider (scene-card, movie-card, performer-card), it will probably look weird 🤔 

YML idea:
```yml
name: customise_plugin
description: Return something
version: 0.1.0
exec:
  - python
  - "{pluginDir}/customise_plug.py"
interface: raw
customize: #(customize instead of task/hook)
  - name: 'IMDB Top Movie'
    description: 'Top rated movie from IMDB' #(Text that will also appear as title of the slider)
    type: 'movies' #(can be studio, performers, movies, scenes, ... )
    defaultArgs:
      mode: imdb_movies
  - name: 'Youtube trending'
    description: 'Trending videos from Youtube'
    type: 'scenes'
    defaultArgs:
      mode: yt_trending
```

Since the data could come from anywhere, there is probably data that the user don't have in the database (performer name, tags, ...). Stash should ignore these things that are not in the database, the best would be to show the name without doing anything (user can't click on it). 

When the user click on the movie/scene/performer, it will open a external url given by the plugin. (Maybe a popup warning to warn the user that it will open a external link ?)

**Describe alternatives you've considered**
Could be expend to a simple yml scraper, a thing like `sceneByName` (because it give a list) but without the user input.

**Additional context**
Could be used to show trending scene from StashDB, showing recent release scene from all network and more 😄
