### ISSUE TITLE
[Feature] Option to disable Movies/Scenes and Galleries inputs from Scene Edit page

### ISSUE THREAD

**Issue by Skier23** [stashapp/stash#2870]
**Is your feature request related to a problem? Please describe.**
It would be nice to disable the input options for Movies/Scenes and Galleries on the scene edit page for people that don't use these features so that there would be more room for the other relevant info.

**Describe the solution you'd like**
Option to disable these fields

**Describe alternatives you've considered**
Currently just living with it how it is.

**Additional context**
N/A

**Comment by 7dJx1qP** [comment]
You can use this custom css to hide those inputs
```css
#scene-edit-details > form > .form-container > div > .form-group:nth-child(5),
#scene-edit-details > form > .form-container > div > .form-group:nth-child(8) {
    display: none;
}
```
