### ISSUE TITLE
[Bug Report] On Local network, The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by twist3dimages** [stashapp/stash#3334]
**Describe the bug**
Every time I view stash (Chrome, Firefox, Edge, Opera) when going to the ip:port, I get "The media could not be loaded, either because the server or network failed or because the format is not supported." None of the thumbnails work. If I go to stash.customdomain.com, it works. I've regenerated the files which didn't fix it
**To Reproduce**
1. Go to IP:9999 of my server
2. Click on any media item
3. Try and play
"The media could not be loaded, either because the server or network failed or because the format is not supported."
**Expected behavior**
I would expect being able to view and play files
**Screenshots**
![image](https://user-images.githubusercontent.com/33134502/210294736-ea731aec-72c0-440e-9fec-107ed668db52.png)

If applicable, add screenshots to help explain your problem please ensure that your screenshots are SFW or at least appropriately censored.

**Stash Version: (from Settings -> About):**

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser Chrome, Edge, Firefox, Opera
 - Version latest

**Additional context**

**Comment by ALonelyJuicebox** [comment]
- Where is your Stash being hosted from?
- Where are your media files located? On a NAS? On a local drive?
- Where does your config.yml expect your /generated/ folder to be?
- Click on a file, click on the **File Info** tab. Is the path that's shown a valid path for your content?

>  If I go to stash.customdomain.com, it works.

Have you mapped your Stash to a DNS entry? What's the custom domain for?

**Comment by billouetaudrey** [comment]
Hi,

I have same issue but on reverse proxy only, work on local, anyone have the fix please ?

**Comment by phyco88** [comment]
Same issue with reverse proxy

**Comment by DogmaDragon** [comment]
Have you set `external_host`?
https://docs.stashapp.cc/guides/reverse-proxy/#setting-external-url

**Comment by billouetaudrey** [comment]
> Hi,
> 
> I have same issue but on reverse proxy only, work on local, anyone have the fix please ?

Work for me but I don't remember how... Can share my apache2 settings if you want

**Comment by phyco88** [comment]
I followed the documentation. I added external_host=https://url.mydomain.com
I added X-Forwarded-For = https and X-Forwarded-Proto = / to my kemp loadmaster headers

Now the video previews work, but the video still does not play, in the browser network tab and curl results I get a 404 now for the stream. 

Even worse now when i go direst IP i get the same issue. I even tried to delete the external_host=https://url.mydomain.com and I'm getting the same issue with going directly to the IP.

any ideas?

**Comment by phyco88** [comment]
LOL sorry stupid me, editing the stack in portainer to add the external_host removed the volume for my data when I updated the stack. Added the volume and rescan did the trick.
thanks everyone.

**Comment by billouetaudrey** [comment]
```
services:
# APPNICENAME=Stash
# APPDESCRIPTION=An organizer for your porn, written in Go
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "9999:9999"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash

      ## Keep configs, scrapers, and plugins here.
      - ./config:/root/.stash
      ## Point this at your collection.
      - ./data:/data
      ## This is where your stash's metadata lives
      - ./metadata:/metadata
      ## Any other cache content.
      - ./cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ./blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ./generated:/generated
      ## Folder
      - /mnt:/mnt
    labels:
      - com.centurylinklabs.watchtower.enable=true
```
