### ISSUE TITLE
Add POST support to scraper queries

### ISSUE THREAD

**Issue by timo95** [stashapp/stash#3361]
**Is your feature request related to a problem? Please describe.**
Some APIs only support API requests as POST query (e.g. [AniList](https://anilist.gitbook.io/anilist-apiv2-docs/overview/graphql/getting-started)). Currently you have to write a script scraper for those.

**Describe the solution you'd like**
In addition to `queryURL`/`queryURLReplace` add `queryBody`/`queryBodyReplace` with the same `{}` placeholder system. Since GET requests technically also allow bodies, another variable `queryHttpMethod` defaulting to `GET` can be used to differentiate between POST and GET.

**Describe alternatives you've considered**
Use python.

**Additional context**
Example query for AniList:
```
sceneByName:
  action: scrapeJson
  queryHttpMethod: POST
  queryURL: https://graphql.anilist.co
  queryBody: {"query":"query($title:String){Media(search:$title,type:ANIME){id,title{english,romaji},tags{name}}}","variables":{"title":{}}}
  scraper: sceneSearch

jsonScrapers:
  sceneSearch:
  ...
```
With the `{}` at the end being replaced by the search string.
