### ISSUE TITLE
[Feature] Ability to set viewport dimensions for CDP scraper

### ISSUE THREAD

**Issue by badchoices** [stashapp/stash#3750]
**Is your feature request related to a problem? Please describe.**
When scraping scenes I have a site that has a UI that is much easier to scrape when it is in the mobile view, the only way to force it is by setting the view port size...

**Describe the solution you'd like**
Under the scraper config.yaml file add the following lines to the `driver` section

```yml
driver:
  useCDP: true
  sleep: 2
  viewport:       # <--
    width: 438    # <--
    height: 1200  # <--
```

**Describe alternatives you've considered**
Force setting CDP to a particular viewport but that is not possible
