### ISSUE TITLE
[Bug Report] Error: Panic: initializing configuration: While parsing config: yaml: line 27: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Sitbatco** [stashapp/stash#3848]
**Describe the bug**
When launching stash-win.exe, i get the following error in the screenshot and stashapp is unable to start and I get the following message:  Error: Panic: initializing configuration: While parsing config: yaml: line 27: mapping values are not allowed in this context

 I'm not sure what happened as it was working before hand. I'm on a Windows 11 PC 

**Screenshots**
![image](https://github.com/stashapp/stash/assets/137430437/498b5602-2749-4cce-addc-7d1ee31d3d46)

**Comment by Sitbatco** [comment]
Which config file should I look at? I tried looking for a config.yaml but I couldn't find anything, and there seems to be several config.go files in different folders thanks!

**Comment by Sitbatco** [comment]
Good point. When starting the CMD, its giving me a blank terminal then the error:
![image](https://github.com/stashapp/stash/assets/137430437/3723961d-fe42-4cb9-8a3f-667d14004a7b)

I didn't download anything else as Stashapp was working perfectly well until today for some reason. (To find the .go files I just searched the folder for config and that was all I found)

**Comment by MrX292** [comment]
Can you open CMD and then put the full path of stash- win.exe in it and hit enter.

**Comment by Sitbatco** [comment]
Good idea I got a bit more information than before:

![image](https://github.com/stashapp/stash/assets/137430437/915eb01b-3e99-4f13-bc0c-3bf15823f516)

**Comment by MrX292** [comment]
The config.yml should either be in  `C:\users\user\.stash` or in the same folder as the executable.

**Comment by Sitbatco** [comment]
Okay got Line 27 and a bit onwards
![image](https://github.com/stashapp/stash/assets/137430437/c1bbf225-cf62-4ad3-a159-d2e6bbe97572)

Line 27 starts at sceneids: []

**Comment by MrX292** [comment]
i think the indentation is wrong.
```
  generate_task:
    covers: true
    sprites: true
    previews: true
    imagepreviews: false
    previewoptions:
      previewsegments: 12
      previewsegmentduration: 0.75
      previewexcludestart: "0"
      previewexcludeend: "0"
      previewpreset: slow
    markers: true
    markerimagepreviews: false
    markerscreenshots: false
    transcodes: false
    forcetranscodes: false
    phashes: true
    interactiveheatmapsspeeds: true
    clippreviews: true
    sceneids: []
    markerids: []
    overwrite: false
```
if line 26 is `clippreviews: true` then 27 should have the same distance like the one from above.
