### ISSUE TITLE
[Feature] [Scraper Development] Expand the scope of the variable fields in xPathScrapers

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#3887]
**Is your feature request related to a problem? Please describe.**
There's currently no way to access the URL of a scene or gallery within _xPathScrapers_ unless the base URL can be pulled from the source (which is frequently not always the case in my experience, eg. Karups).

Use cases: 1. Attempting to scrape a studio code when it's only available in the URL. 2. Sanitizing the URL (removing referral codes and other irrelevant parameters in the URL)

**Describe the solution you'd like**
(1) Allow us to pass _&{fields}_ objects from one section of the scraper to another. Eg

Declare the `&url` object
```
sceneByURL:
  - action: scrapeXPath
    url: &url
      - domain.com/video/
```
Recall the declared value  with `*url`
```
xPathScrapers:
  sceneScraper:
    scene:
      URL: *url       <--- This currently will break the scraper with an unmarshal error
```
