### ISSUE TITLE
[Bug Report] Incorrect scene cover height

### ISSUE THREAD

**Issue by MasterHarem** [stashapp/stash#4238]
**Describe the bug**
On mobile (also on a desktop in mobile mode) we see that the height of the cover is too high, when we want to watch the preview it seems to have the right height.

**To Reproduce**
1. Go to Scene (on mobile)
2. See error

**Expected behavior**
A correct cover height.

**Screenshots**
![Capture d'écran 2023-10-24 093833](https://github.com/stashapp/stash/assets/69746920/cbb37117-3188-4f61-825f-6dd952677ffd)

![Capture d'écran 2023-10-24 094158](https://github.com/stashapp/stash/assets/69746920/4bdf70b5-3319-476d-9cb6-12fef82f5524)

**Stash Version:** v0.23.1

**Smartphone:**
 - Device: OnePlus 8 Pro
 - OS: OxigenOS 13.1 / Android 13
 - Browser Google Chrome
 - Version 118.0.5993.80

**Comment by MasterHarem** [comment]
I see that it is a problem related to the Modern Dark theme, I am using version 1.2, when I deactivate the custom css the height is correct

**Comment by MasterHarem** [comment]
```css
 @media (max-width: 575.98px) and (orientation: portrait) {
     .scene-card-preview-image {
         height: calc(100vw * (9 / 16));
    }
```

After analysis I see that the problem is this property, if I deactivate it everything works correctly
