### ISSUE TITLE
[Feature] Add "disambiguating" select values to scene, gallery, and movie select dropdowns

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#4790]
**Is your feature request related to a problem? Please describe.**
Nothing precludes duplicate titles for scene, gallery, or movie objects. Therefore, dropdown select values of each may contain duplicate string values that are impossible to differentiate from one another.

_Example of official duplicate gallery titles from ATK_
![image](https://github.com/stashapp/stash/assets/37937507/088563eb-b2c1-4b39-9c9e-79f8e0a4c2d9)

This is more prevalent among particular studios that heavily recycle titles, but regardless, given enough content, just as with performer names, duplicates emerge.

**Describe the solution you'd like**
Display complimentary metadata to disambiguate each select title value in the drop down.

- Date
- Studio code
- Cover image, just as implemented in #4227 

A tiny thumbnail of a cover image may seem irrelevant due to its size, but consider small distinctions in colors and shapes would be enough to disambiguate it from other cover images all other values being equal.

![image](https://github.com/stashapp/stash/assets/37937507/3fa1984b-f804-4b92-ba87-54ce54e40d60)

Styling should consider the following:
- Keep height of select consistent with the performer select (#4227)
- Title select value should take precedence (ie. white color)
- Complimentary select values are secondary, and can be conveniently presented below title value with a muted color

For example, something like:

```css
.select-options {

     /* Set default styling for all span elements */
     span {
          color: white;
          display: block;
     }

     span.select-option-title {
     }

     /* Mute text of complimentary metadata span elements */
     span.select-option-date,
     span.select-option-studio_code {
          opacity: 0.7;
     }

}
```

**Additional context**
I should have included this broad request in my initial request https://github.com/stashapp/stash/issues/3076 (_to add performer images to the performer select_) implemented here https://github.com/stashapp/stash/pull/4227, since it falls under the same conceptual umbrella.

Side note: if studio objects ever have the ability to either use non-unique names or can have favicons, this concept should be applied to them as well since duplicate studio names do exist (outside of Stash).

```html
<select-options>
  <div class="primary line">
        <img>$favicon</img> <span>$studio_name</span>
  </div>
  <div class="secondary line">
        <span>$parent_studios</span>
  </div>
</select-options>
```
