### ISSUE TITLE
[Feature] Configuration to select displayed tabs in Scene page

### ISSUE THREAD

**Issue by S3L3CT3DLoves** [stashapp/stash#4916]
**Is your feature request related to a problem? Please describe.**
The page to view a scene is getting more tabs, most of them are just clutter to me, and cause me to misclick often.

**Describe the solution you'd like**
Similar to the ability to enable/disable Movies/Images/... could we have a menu configuration to enable/disable tabs in the Scene page ?
For example, I would like to hide the Markers, Filters, History tabs, I never use them...

**Comment by echo6ix** [comment]
Custom CSS

```css
.scene-tabs {
    [data-rb-event-key=scene-markers-panel],
    [data-rb-event-key=scene-history-panel],
    [data-rb-event-key=scene-video-filter-panel] {
        display: none;
    } 
}
```
