### ISSUE TITLE
[Feature] Image viewer too small on mobile

### ISSUE THREAD

**Issue by timetraffic10** [stashapp/stash#5475]
**Is your feature request related to a problem? Please describe.**
As primarily a mobile user of Stash, and mainly using images. When you view an image in Stash, there's a lot of space used by the interface rather than just showing the image. When you zoom in, this often produces a "tap" on the screen and changes the image, or moves the image elsewhere on the screen.

**Describe the solution you'd like**
Ideally the ability to move into a "full screen" mode where all the interface is removed aside from an "exit" function. You can still use the tap funtion to slide between images.

**Describe alternatives you've considered**
I previously used PiGallery2, and they had a good implementation of a full sized image, so you're not losing image real estate to interface

**Additional context**
I've attached a (Safe!) screenshot so you can see what I mean, due to the surrounding interface, the image is using a fraction of the screen. This is taken on an iPhone.
![IMG_0196](https://github.com/user-attachments/assets/a188f34d-5862-4db0-b030-b105e7e8d844)

**Comment by kyuu840** [comment]
A workaround: add this to the custom CSS in Settings > Interface.
[[Reference](https://docs.stashapp.cc/user-interface-ui/custom-css-snippets/#hide-the-lightbox-header-and-footer)]
```css
/* [Gallery tab] Hides the lightbox header and footer to make the image area larger. Mouse reveals them as an overlay to the image*/

.Lightbox-header,
.Lightbox-footer{
z-index:9999;
 position:absolute;
 width:100%;
 opacity:0;
background-color:#0008;
 transition: opacity 0.5s ease;
}

.Lightbox-footer{
bottom:0;}

.Lightbox-navbutton{
opacity:0;
transition: opacity 0.5s ease;
}

.Lightbox-navbutton:hover,
.Lightbox-header:hover,
.Lightbox-footer:hover{
opacity:1;
}
```
