### ISSUE TITLE
Scraping duplicate tags

### ISSUE THREAD

**Issue by Maista6969** [stashapp/stash#5730]
This bug occurs when scraping a scene from any source where the remote tags have been aliased to a single local tag, for example if the studio has the tags "Blue" and "Red" but the user has a local tag called "Color" that contains the aliases "Blue" and "Red"

In this case the `findTags` query will attempt to find the same ID twice and will error out and show the user an erroneously empty tags field in their scrape result

**Steps to reproduce**
The easiest way to reproduce this is to run a `findTags` query with an array containing duplicate IDs
```gql
{
  findTags(ids: [1, 1]) {
    tags {
      name
    }
  }
}
```

The full process as observed by a user is as follows:

On a blank instance of Stash, create a new tag called "Color" and give it the aliases "Red" and "Blue"

![Image](https://github.com/user-attachments/assets/fde817e9-3175-4626-9214-3d17e286a196)

Add this example scraper:
```yml
name: Duplicate Tag Bug
sceneByFragment:
  action: scrapeXPath
  scraper: example
  queryURL: https://example.com/
xPathScrapers:
  example:
    scene:
      Details:
        fixed: This scraper will demonstrate the bug with multiple tags
      Tags:
        Name:
          selector: //h1
          postProcess:
            - javascript: return "Blue, Red"
          split: ", "
```
 
Then trigger a scrape and verify that the Tags field is empty

![Image](https://github.com/user-attachments/assets/dc3ce8db-626e-4774-b676-60f9a716ee21)

![Image](https://github.com/user-attachments/assets/a509e7b2-274e-4fdc-b83e-e41c766375bd)

Inspecting the request in browser developer tools shows that the scraper returns the results as expected but the subsequent `findTags` fails because the ID for the Color tag appears twice in the array of IDs

![Image](https://github.com/user-attachments/assets/7a414935-039a-4f24-9bd1-3ff6bc802afb)

![Image](https://github.com/user-attachments/assets/44661372-abbb-4b35-b074-d7524260d698)

**Expected behavior**
When the user has aliased the tags "Red" and "Blue" to "Color" we'd expect to see the "Color" tag appear as a result

**Stash Version:**
v0.27.2-91-gc2bc3138
