### ISSUE TITLE
[Feature] non-privileged user in Docker build

### ISSUE THREAD

**Issue by piramiday** [stashapp/stash#684]
**Is your feature request related to a problem? Please describe.**
at present, `stash` is running as root in the Docker container.

**Describe the solution you'd like**
ideally, a new non-privileged user should be created to execute `stash`, so that root permissions are dropped asap.

a non-root user for `stash` would agree with best practices and provide tighter security.
if possible, it would be great to be able to control both UID and GID of any created file.

**Comment by piramiday** [comment]
bump?

**Comment by virusperfect** [comment]
I would love to see that feature as well. Either by allowing the --user option or by having environment variables PUID and PGID.

**Comment by devster31** [comment]
Can be potentially solved by the following:
```yml
services:
  stash:
    command: stash --config /config/config.yml
    ...
    environment:
      - USER=user
      - HOME=/config
    ...
    user: 1000:1000
    ...
```
