### ISSUE TITLE
[Feature] Common field post-processing scraper enhancement

### ISSUE THREAD

**Issue by echo6ix** [stashapp/stash#761]
**Is your feature request related to a problem? Please describe.**
Suppose you're building a scraper that parses many websites that belong to the same studio. All the web sites follow the same structure, except they use a different base url (such as `www.google.com` or `www.duckduckgo.com`). Sometimes when scraping for the image on these sites it's impossible to get anything but the relative url, (such as `/image/thumb.gif`).

If our scraper were only ever dealing with one web site, we could hard code the base url for the image in post-processing, but when dealing with multiple sites, there's no way for our scraper to know which of the sites we're dealing with so we cannot hard code the base url.

**Describe the solution you'd like**
Either,

1. Create a constant, such as $domain, that contains the value of the base url that is being scraped based off the url being scraped. So if the scene provided is http://www.domain.com/videos/scene.html, then $domain would contain `http://www.domain.com`, or

2. A more flexible solution (assuming it's feasible and doesn't break anything), allow post-processing for common fields so users can just make their own custom variables containing a base url. Here's an example of a simple one that could work (taken from Zenvo's example on Discord for expedience):

```
Common:
        $site: 
          selector: //base/@href
          postProcess: 
            - replace: 
              - regex: /tour/
                with: 
            - replace: 
              - regex: http://
                with: https://

```
And then
```
Image:
        selector: //script[contains(.,'jwplayer("jwbox").setup')]/text()
        replace:
          - regex: (.+image:\s+")(.+jpg)(.+)
            with: $2
          - regex: ^
            with: $site
      
```
