### ISSUE TITLE
Safe Mode CSS snippet

### ISSUE THREAD

**Issue by cafuneandchill** [stashapp/stash#868]
Hello!

I wrote a CSS snippet that removes all video previews and images, so that you can work with Stash (edit metadata, add other data) in a possibly NSFW-sensitive environment. You can use it just like any other custom CSS snippet, as explained in the [wiki](https://github.com/stashapp/stash/wiki/Custom-CSS-snippets).

It is possible that the snippet may require more work, in case it breaks in some edge cases.

```css
/*
Safe Mode:
    - removes all video and previews in Scenes
    - removes the video player when you click any of the Scenes,
    so you can edit the metadata without having to see the video
*/

.image-thumbnail {
    display: none
}

.scene-card-video,
.gallery-card-image,
.tag-card-image {
  display: none
}

.scene-cover {
    display: none;
}

.jw-media,
.jw-preview {
 display: none
}

.scene-player-container {
    display: none;
}

.scene-tabs {
    flex: 0 0 100%;
    max-width: 100%;
}

.wall {
    display: none
}
```
